# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=10)),
                ('initial_date', models.DateTimeField()),
                ('final_date', models.DateTimeField()),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmation_date', models.DateTimeField()),
                ('deposit', models.BooleanField(default=False)),
                ('invoice', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
