# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre y apellidos')),
                ('dni', models.CharField(max_length=64, verbose_name='D.N.I. o pasaporte')),
                ('email', models.CharField(max_length=64, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=64, verbose_name='Número de teléfono')),
                ('initial_date', models.DateField(verbose_name='Fecha de entrada')),
                ('final_date', models.DateField(verbose_name='Fecha de salida')),
                ('guests', models.PositiveSmallIntegerField(verbose_name='Número de huéspedes')),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de reserva')),
                ('reference', models.CharField(max_length=8, verbose_name='Localizador')),
                ('confirmation_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de confirmación')),
                ('deposit', models.BooleanField(default=False, verbose_name='Fianza pagada')),
                ('invoice', models.BooleanField(default=False, verbose_name='Factura final pagada')),
            ],
            options={
                'verbose_name_plural': 'reservas',
                'verbose_name': 'reserva',
                'ordering': ['initial_date'],
            },
        ),
    ]
