# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='final_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='initial_date',
            field=models.DateField(),
        ),
    ]
