# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20160705_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
