# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20160705_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='author',
        ),
    ]
