# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_reservation_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['initial_date'], 'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.CharField(default='falso', max_length=64, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.BigIntegerField(default=666777888, verbose_name='Número de teléfono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reference',
            field=models.CharField(default='refREFrefR', max_length=8, verbose_name='Localizador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de confirmación'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='deposit',
            field=models.BooleanField(default=False, verbose_name='Fianza pagada'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dni',
            field=models.CharField(max_length=32, verbose_name='D.N.I. o pasaporte'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='final_date',
            field=models.DateField(verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='initial_date',
            field=models.DateField(verbose_name='Fecha de entrada'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='invoice',
            field=models.BooleanField(default=False, verbose_name='Factura final pagada'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre y apellidos'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de reserva'),
        ),
    ]
