# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20160706_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Número de teléfono'),
        ),
    ]
